### PR TITLE
Update Elasticsearch to 2.1

### PR DESCRIPTION
**Pull request by nuest**

### CODE REVIEW

**Comment by nuest** [comment]
guave version change is OK by @CarstenHollmann afaik.

**Comment by nuest** [comment]
Since spring was updated, are all the schemas in the configuration files updated, too?

**Comment by nuest** [comment]
@autermann Do you see any issues in merging this? we actually need a release soon for a downstream service...

**Comment by autermann** [comment]
Looks good to me... Should I merge this immediately, or is there anything left?

**Comment by nuest** [comment]
@CarstenHollmann do these changes work with SOS 5.x ? If so, then we ( @matthesrieke and I) hope this is all.

**Comment by CarstenHollmann** [comment]
@nuest When checking with the SOS 5.x I noticed that there are some new 3rd party libs. Most of them are under Apache 2.0 but two are under a different licenses.

@matthesrieke Can we use these licenses in GPL and Apache projects?

Here are the two 3rd party libs (from NOTICE file):
* HdrHistogram under Public Domain, per Creative Commons CC0
* JSR166e under CC0 1.0 Universal

**Comment by autermann** [comment]
CC0 should be fine in about any project :smile:

**Comment by nuest** [comment]
The arguments supporting @autermann are here: https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

**Comment by CarstenHollmann** [comment]
Now the changes works with SOS 5.x. 
@autermann You can merge the changes

**Pull request merged**
