### PR TITLE
Remove SOS specifics

### LINKED ISSUE #17: Remove SOS specific classes
* https://github.com/52North/iceland/search?utf8=%E2%9C%93&q=sos
* https://github.com/52North/iceland/search?utf8=%E2%9C%93&q=sensor&type=Code

### PR DESCRIPTION
**Pull request by nuest**
I added a few more deprecation tags to SOS-specific things, and renamed "..Swe" methods that functionally are already more generic.

Renamed comments where possible as well.

This shall not stop a first release of iceland, so let's use this pull request to straighten some things out!

Fixes #17

### CODE REVIEW

**Comment by nuest** [comment]
What is the matter with this https://github.com/52North/iceland/blob/develop/core/src/main/java/org/n52/iceland/util/JavaHelper.java#L61 line - is the method ``getSubclasses(Class<T> clazz)`` actually in use somewhere?

**Comment by autermann** [comment]
> What is the matter with [this](https://github.com/52North/iceland/blob/develop/core/src/main/java/org/n52/iceland/util/JavaHelper.java#L61) line - is the method getSubclasses(Class<T> clazz) actually in use somewhere?

That's a classic case of bad things happening in static methods... @CarstenHollmann Is this still used in the SOS?

**Comment by CarstenHollmann** [comment]
Probably not. I have nowhere found a call for the method in the SOS 4.x. So I'm assuming that it is not used in SOS 5.x.

**Comment by autermann** [comment]
@nuest Could you remove the method, the initialization and the dependency declarations[[1](https://github.com/52North/iceland/blob/3e903fcb8beebf4451431057e9aca1b74d54604a/pom.xml#L215)][[2](https://github.com/52North/iceland/blob/cc1198c02bd0fd3373c57e330b2280f89ea0a462/core/pom.xml#L84)]?

**Comment by autermann** [comment]
btw: nice branch name ;)

**Comment by EHJ-52n** [comment]
By the way, using SHA-1 is not good, too. 

https://github.com/52North/iceland/blob/develop/core/src/main/java/org/n52/iceland/util/JavaHelper.java#L60

https://www.quora.com/Cryptography/Why-are-MD5-and-SHA1-called-broken-algorithms

**Comment by nuest** [comment]
@EHJ-52n That method was just removed :-)

**Pull request merged**
